### ISSUE TITLE
`result` object structure in Firefox

### ISSUE THREAD

**Issue by igor-starostenko-ag** [wolverineks/react-use-async#21]
For some reason, in Firefox `result` object is different.

For example:
```
const { result } = useAsync(
  async () => anyAsyncFunction(),
  [],
);

console.log(result);
// { _a: undefined, _c: Array [], _d: true, _h: 0, _n: false, _s: 1, _v: [] }
```

The `_v` in this case corresponds to the value that is returned from resolved promise.

**Comment by wolverineks** [comment]
Not sure about this. Looks like you might be talking about a different `useAsync` library.
This `useAsync` doesnt take any arguments.
